name: dxWDL compile
author: DNAnexus
description: Compile a WDL workflow with dxWDL
inputs:
  wdl:
    description: The main WDL file
    required: true
  destination:
    description: Destination project and folder
    required: true
  archive:
    description: How to deal with existing workflows/applets (-archive or -force)
    required: true
    default: true
  locked:
    description: Create a locked workflow
    required: true
    default: false
  streamAllFiles:
    description: Mount all files with dxfuse - do not use the download agent
    required: true
    default: true
  api_token:
    description: DNAnexus API token
    required: true
  apiserver_protocol:
    description: DNAnexus API server protocol
    required: true
    default: https
  apiserver_host:
    description: DNAnexus API server hostname
    required: true
    default: api.dnanexus.com
  apiserver_port:
    description: DNAnexus API server port
    required: true
    default: 443
  runs:
    using: docker
    image: docker://dnanexus/dxwdl@sha:b475c64898626c681ac81496fe287d9f822f9d27eea448793dfe04f5eca77280
    env:
      DX_SECURITY_CONTEXT: '{"auth_token": "${{ inputs.api_token }}", "auth_token_type": "bearer"}'
      DX_APISERVER_PROTOCOL: ${{ apiserver_protocol }}
      DX_APISERVER_HOST: ${{ apiserver_host }}
      DX_APISERVER_PORT: ${{ apiserver_port }}
    args:
      - ${{ inputs.wdl }}
      - -destination
      - ${{ inputs.destination }}
      - ${{ inputs.archive ? '-archive' | '-f' }}
      - ${{ inputs.locked ? '-locked' | '' }}
      - ${{ inputs.streamAllFiles ? '-streamAllFiles' | '' }}
