name: 'dxWDL compile'
author: 'DNAnexus'
description: 'Compile a WDL workflow with dxWDL'
inputs:
  wdl:
    description: 'The main WDL file'
    required: true
  destination:
    description: 'Destination project and folder'
    required: true
  extra_args:
    description: 'Additional arguments to dxWDL'
    required: false
    default: '-archive -streamAllFiles'
  api_token:
    description: 'DNAnexus API token'
    required: true
  apiserver_protocol:
    description: 'DNAnexus API server protocol'
    required: true
    default: 'https'
  apiserver_host:
    description: 'DNAnexus API server hostname'
    required: true
    default: 'api.dnanexus.com'
  apiserver_port:
    description: 'DNAnexus API server port'
    required: true
    default: '443'
runs:
  using: 'docker'
  image: 'docker://dnanexus/dxwdl@sha256:b475c64898626c681ac81496fe287d9f822f9d27eea448793dfe04f5eca77280'
  args:
    - ${{ inputs.wdl }}
    - '-destination'
    - ${{ inputs.destination }}
    - ${{ inputs.extra_args }}
  env:
    DX_SECURITY_CONTEXT: '{"auth_token": "${{ inputs.api_token }}", "auth_token_type": "bearer"}'
    DX_APISERVER_PROTOCOL: ${{ inputs.apiserver_protocol }}
    DX_APISERVER_HOST: ${{ inputs.apiserver_host }}
    DX_APISERVER_PORT: ${{ inputs.apiserver_port }}