name: Master Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Workflow
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile hello.wdl
        uses: .github/actions/dxwdl-compile
        with:
          wdl: hello.wdl
          token: ${{ secrets.API_TOKEN }}

